### ISSUE TITLE
Support for class methods

### ISSUE THREAD

**Issue by hdf1996** [joelmoss/delivered#3]
Hi! First of all I loved the idea so far, thanks for making it open source! I also thought of something like this but I never actually implemented it. Sorbet is a little bit heavy lift and RBS is too far from runtime to me, but this is a simple implementation. I even think it may be eventually be able to export to RBS for IDE support (an entirely different conversation, but wanted to mention it)

While trying it out i found out it does not have support  for class methods. Here's an example on how to reproduce

```ruby
require 'delivered'

class User
  extend Delivered::Signature

  sig String, age: Integer, returns: String
  def initialize(name, age:)
      "User #{name} created with age #{age}"
  end

  sig String, returns: String
  def self.example(user)
      123
  end
end

User.example(1)
# should throw error because of the integer as parameter, and also because of the integer as returned value
```

I may be able to submit a PR for this in the short term, but wanted to submit the issue first, in case you or someone else wants to do it before

**Comment by joelmoss** [comment]
More than happy for you to submit a PR, thx. I would expect that I would need this in not too distant future
