### ISSUE TITLE
Replace and avoid possible conflict of `returns` kwarg

### ISSUE THREAD

**Issue by joelmoss** [joelmoss/delivered#5]
Currently `sig` uses a `returns` keyword arg, which can obviously conflict. We can change it to one of the following, but not sure which… 🤔

```ruby
sig [String, age: Integer] => User
```

or…

```ruby
sig(String, age: Integer) { User }
```

... or both!

**Comment by hdf1996** [comment]
Voting for the second option! In the hypotetic case the type is multiline (not common, but could happen), that's easier to read and to delimit it. 

Also, suporting both sounds possible, but I think it could get messy pretty fast, so I would say to support just one of them

**Comment by joelmoss** [comment]
I kinda like the first, mainly because of the use of hashrocket `=>` gives me the visual idea that what follows is returned.
