### ISSUE TITLE
Boolean support

### ISSUE THREAD

**Issue by hdf1996** [joelmoss/delivered#6]
Hi! Curious if boolean types are supported in this implementation, and if so how it'll be done on the `sig call`. Specifically asking because 
Boolean type doesn't exist as such.

```ruby
sig Boolean, returns: Boolean
def something(b)
  !b
end
```

Some alternatives if that's not implemented, can be to create a class to be used as type like Sorbet or RBS does `Types::Boolean` or `Bool`

**Comment by joelmoss** [comment]
Watch this space 👀
